### ISSUE TITLE
Method "getdate()" returns "None" for valid dateString for psycopg2 connection

### ISSUE THREAD

**Issue by pepperblue** [chrthomsen/pygrametl#6] opened 2016-08-22 13:00 UTC
Using latest pygrametl, Python 3.5, psycopg2 2.6.2 method "getdate()" returns "None" for dateString of format yyyy-mm-dd. Root of the problem is - as far as I was able to track down this issue - that method "ConnectionWrapper.getunderlyingmodule()" is returning "psycopg2.extensions" where no method Date() is present ...

**Comment by skejserjensen** [comment] 2016-08-22 16:28
It would seem the problem is caused by a change in psycopg2 2.6 as `connection.__class__`  return `psycopg2.extensions.connection` instead of `psycopg2._psycopg.connection` as in psycopg2 2.5.5.

This unfortunately means we properly will have to find another method for locating `Date` that does not rely on the relative location of `Date` and `Connection` if we want to support both versions in addition to database driver for other database management systems.

One way to circumvent the bug until a fix is in place could be to downgrade psycopg2 to a version from the 2.5 series if that is possible in your case.

**Closed** 2016-08-23 08:02 UTC
