### ISSUE TITLE
How to insert multiple rows at the same time using sql

### ISSUE THREAD

**Issue by qianxuanyon** [chrthomsen/pygrametl#19] opened 2020-02-14 08:08 UTC
I want to achieve this 
````sql
> INSERT INTO `userTable` (`user_id`, `user_name`) VALUES
> (1, 'dsf'),
> (2, 'fgy'),
> (3, 'faad');

Hope to have a simple example

**Comment by chrthomsen** [comment] 2020-02-14 08:49
Do you just want to be able to execute the shown SQL or if you are looking for ways to make pygrametl Dimensions/FactTables do batch inserts?

**Comment by qianxuanyon** [comment] 2020-02-14 09:07
> Do you just want to be able to execute the shown SQL or if you are looking for ways to make pygrametl Dimensions/FactTables do batch inserts?

pygrametl Dimensions/FactTables do batch inserts
I expected it to be inserting multiple rows at once, like my example

![image](https://user-images.githubusercontent.com/29041881/74517075-7955db00-4f4c-11ea-9407-6e8a42a170d2.png)

**Comment by chrthomsen** [comment] 2020-02-14 09:15
That probably depends on your PEP249 module. BacthFactTable uses the PEP249 cursor's executemany method. According to the PEP249 documentation

> Modules are free to implement this method using multiple calls to the .execute() method or by using array operations to have the database process the sequence as a whole in one call.

**Comment by qianxuanyon** [comment] 2020-02-14 09:37
> That probably depends on your PEP249 module. BacthFactTable uses the PEP249 cursor's executemany method. According to the PEP249 documentation
> 
> > Modules are free to implement this method using multiple calls to the .execute() method or by using array operations to have the database process the sequence as a whole in one call.


I am using pyhive's presto executemany method can be used

So is there any way to make the insertion speed faster? 

I just want to find an easy way to batch insert When there is no Bulk Loading method

![image](https://user-images.githubusercontent.com/29041881/74519392-8e346d80-4f50-11ea-80ca-42afbab403fe.png)

**Comment by skejserjensen** [comment] 2020-02-17 12:20
I have looked at the PEP 249 connectors listed on Presto's [homepage](https://prestodb.io/resources.html#language-python)  and [PyHive](https://github.com/dropbox/PyHive/blob/master/pyhive/common.py#L79) seems to be using a loop with multiple calls to `execute()` while [presto-python-client](https://github.com/prestodb/presto-python-client/blob/master/prestodb/dbapi.py#L240) simply raises an exception if `executeMany()` is called. A quick look through PEP 249 connectors for other systems indicates that the problem is not exclusive to Presto, so adding support for inserting batches using one insert statement seems like a useful addition to pygrametl. As a quick and dirty fix right now I have created this alternative implementation of `BatchFactTable.__insertnow()`. 

```python
def __insertnow(self):
    rowToValue = lambda row: '(' + ','.join(map(lambda c: "'" + row[c]
        + "'" if type(row[c]) is str else str(row[c]), self.all)) + ')'
    values = map(rowToValue, self.__batch)
    basesql = self.insertsql[:self.insertsql.find(' (') + 1]
    insertsql = basesql + ','.join(values)
    self.targetconnection.execute(insertsql)
```
If you decide to try using this version of `__insertnow()` then please report any changes in the performance of your program compared to using the version of `__insertnow()` using `executeMany()`.

**Comment by qianxuanyon** [comment] 2020-02-18 04:09
> I have looked at the PEP 249 connectors listed on Presto's [homepage](https://prestodb.io/resources.html#language-python) and [PyHive](https://github.com/dropbox/PyHive/blob/master/pyhive/common.py#L79) seems to be using a loop with multiple calls to `execute()` while [presto-python-client](https://github.com/prestodb/presto-python-client/blob/master/prestodb/dbapi.py#L240) simply raises an exception if `executeMany()` is called. A quick look through PEP 249 connectors for other systems indicates that the problem is not exclusive to Presto, so adding support for inserting batches using one insert statement seems like a useful addition to pygrametl. As a quick and dirty fix right now I have created this alternative implementation of `BatchFactTable.__insertnow()`.
> 
> ```python
> def __insertnow(self):
>     rowToValue = lambda row: '(' + ','.join(map(lambda c: "'" + row[c]
>         + "'" if type(row[c]) is str else str(row[c]), self.all)) + ')'
>     values = map(rowToValue, self.__batch)
>     basesql = self.insertsql[:self.insertsql.find(' (') + 1]
>     insertsql = basesql + ','.join(values)
>     self.targetconnection.execute(insertsql)
> ```
> 
> If you decide to try using this version of `__insertnow()` then please report any changes in the performance of your program compared to using the version of `__insertnow()` using `executeMany()`.

I tried your method but the result cannot be submitted automatically 

![image](https://user-images.githubusercontent.com/29041881/74703180-5165c080-5247-11ea-97fd-38b4f7a9a91a.png)

**Comment by skejserjensen** [comment] 2020-02-25 08:40
Unfortunately, that seems to be my fault as the method I posted is missing a key feature, it does not delete the current batch after it is inserted. As `BatchFactTable` determines when to load a batch using [equality](https://github.com/chrthomsen/pygrametl/blob/master/pygrametl/tables.py#L1869) only the first batch was loaded automatically. The problem should be fixed in this version, although the last batch should of course still be loaded by executing either `ConnectionWrapper.commit()` or `BatchFactTable.endload()` as it might be smaller than `batchsize`.

```python
def __insertnow(self):
    if self.__batch:
        rowToValue = lambda row: '(' + \
            ','.join(map(lambda c: "'" + row[c] + "'" if type(row[c])
                         is str else str(row[c]), self.all)) + ')'
        values = map(rowToValue, self.__batch)
        basesql = self.insertsql[:self.insertsql.find(' (') + 1]
        insertsql = basesql + ','.join(values)
        self.targetconnection.execute(insertsql)
        self.__batch = []
```

**Closed** 2020-04-14 18:47 UTC
Labels: enhancement, question
